Numerical + python

### 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구

list보다 빠르고 다양한 기능을 제공
- 1차원 데이터(=벡터)
- 2차원 데이터(=매트릭스)
- 3차원 이상 데이터(=텐서, 채널)

np.array를 사용하여 빠른 연산이 가능!!

In [3]:
import numpy as np

In [4]:
# numpy를 사용한 1차원 배열

array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [6]:
# numpy를 사용한 2차원 배열

array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


In [8]:
# 배열 크기 shape

print(array.shape)
print(array_2.shape) # 2행 3열

(4,)
(2, 3)


In [12]:
# 배열 전체의 요소 개수 확인

print(array_2.size)
print(array.size)

6
4


In [11]:
# 배열의 차원 확인 ndim

print(array_2.ndim)
print(array.ndim)

2
1


### 배열 생성하기

In [13]:
arr_zero = np.zeros((3,4)) # 소괄호로 행과 열 지정
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# 1값으로 모두 초기화

arr_one = np.ones((3,4))
print(arr_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# 임의의 값으로 모두 초기화

arr_f = np.full((5,5),"f")
print(arr_f)

[['f' 'f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f' 'f']
 ['f' 'f' 'f' 'f' 'f']]


In [18]:
# 1~50이 담긴 배열

list1 = []
for i in range(1,51):
    list1.append(i)

array_3 = np.array(list1)
print(array_3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [19]:
# 1~50값 입력 arange(시작값, 종료값)

array_4 = np.arange(1,51)
print(array_4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [20]:
# 랜덤 값 배열 생성

arr_ran = np.random.rand(2,3)
print(arr_ran)

[[0.33741317 0.68870636 0.49140667]
 [0.81562379 0.16011162 0.38372016]]


In [21]:
# array 연산

array_5 = np.array([1,2,3])

print(array_5 + array_5)
print(array_5/2.0)
print(array_5*3)

[2 4 6]
[0.5 1.  1.5]
[3 6 9]


In [25]:
with open("height_weight.txt",'r')as f:
    height = f.readline()
    weight = f.readline()
    
print(height) # 175.2,180.3!!!가 하나의 큰 덩어리 데이터
print(weight) # 마찬가지

height = height.split(",")
weight = weight.split(",")
print(height)
print(weight)

#문자열을 숫자로 형변환하는 방법. dtype은 np.array의 타입을 변경
height_np = np.array(height, dtype = np.float64)
weight_np = np.array(weight, dtype = np.float64)

print(height_np)
print(weight_np)

# BMP = 몸무케/키(m) x 키(m), cm인 키를 m로 환산해줘야함
height_np /= 100 
print(height_np)
bmi = weight_np / (height_np*height_np)
print(bmi)

175.2,180.3,175,169.2,185.2,188.0,177.6,178.2,177,179.0

65.6,88.0,79.2,69.3,55.0,71.2,73.0,68.9,74.0,82.0
['175.2', '180.3', '175', '169.2', '185.2', '188.0', '177.6', '178.2', '177', '179.0\n']
['65.6', '88.0', '79.2', '69.3', '55.0', '71.2', '73.0', '68.9', '74.0', '82.0']
[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]
[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [29]:
# 인덱싱

arr1 = np.arange(10)
print(arr1)
print(arr1[0])
print(arr1[-1])

[0 1 2 3 4 5 6 7 8 9]
0
9


In [30]:
# 슬라이싱

print(arr1[2:5])
print(arr1[2:])
print(arr1[:5])
print(arr1[:])

[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [32]:
# reshape(행,렬) 2차원 배열 정의

arr2 = np.arange(50).reshape(5,10)
print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [34]:
print(arr2[2:4]) # 2~4번째 미만의 행 출력
print("=====================")
print(arr2[2:]) # 2번째 행 부터 끝까지
print("=====================")
print(arr2[:4]) # 처음부터 4번째 미만 행 까지
print("====================")
print(arr2[:]) # 전체 출력

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [36]:
print(arr2[:,:]) # 쉼표를 기준으로 행과 열로 나누어짐
print("==============================================")
print(arr2[:2,:]) # 2번째 행 미만 값을 모두 출력
print("==============================================")
print(arr2[:,0]) # 모든 행의 0번째 열만 출력
print("==============================================")
print(arr2[:4,:5]) # 0~4번째 미만의 행에서 0~5번째 미만의 열까지 출력
print("==============================================")
print(arr2[2,1]) # 2행 1열에 있는 데이터 출력

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 0 10 20 30 40]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
21


In [41]:
# boolean 인덱싱 - True값만 출력 해 주는 것 (데이터 시각화)

name = np.array(["1호","2호","3호","4호"])
bol = np.array([True, True, False, False])

print(name[bol])

print(name[name=="1호"]) # True인 데이터만 출력

['1호' '2호']
['1호']


In [40]:
arr3 = np.array([11,22,33,44,55])
print(arr3[arr3>30]) # True인 데이터만 출력

[33 44 55]


In [50]:
# 단일 배열에서 사용되는 함수
arr5 = np.random.rand(5,4)
print(arr5)

print(arr5.sum()) # arr5에 있는 모든 수 더하기
print(arr5.mean()) # 평균 구하기

[[0.29748338 0.12528576 0.74563309 0.73931093]
 [0.18603441 0.27652006 0.97713274 0.97487794]
 [0.37452396 0.9603361  0.7012085  0.15637599]
 [0.08589029 0.85791613 0.95811685 0.6478652 ]
 [0.36405002 0.67319172 0.67167326 0.80861256]]
11.582038877890197
0.5791019438945099


In [53]:
arr6 = np.arange(1,6)
print(arr6)
print(np.sqrt(arr6)) # 제곱근

[1 2 3 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [55]:
arr7 = np.array([-1,5,-11,7,-20])
print(np.abs(arr7)) # 절대값

[ 1  5 11  7 20]


### Numpy를 활용한 영화 리뷰 분석

In [57]:
data = np.loadtxt("ratings_small.dat", delimiter = '::', dtype = np.int64)
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     1779      2502         4 998699749]
 [     1779      3160         5 977032398]
 [     1779      3168         4 977033232]]


In [58]:
print(data.ndim) # 몇 차원 배열인지
print(data.shape) # 몇행 몇열인지
print(data.size) # 배열 전체 요소 개수 확인

2
(300001, 4)
1200004


In [60]:
data[:,2] # 영화 평점인 모든행의 2열을 출력

array([5, 3, 3, ..., 4, 5, 4], dtype=int64)

In [61]:
# 영화 평점의 평균

all_mean = data[:,2].mean()
print(all_mean)

3.5613081289729034


In [64]:
# 중복 값 제거. unique로 유일한 값만 출력 id의 중복된 것들을 제거함
user_id = np.unique(data[:,0])
print(user_id)
print(user_id.size)
print(user_id.shape) # 1779행

[   1    2    3 ... 1777 1778 1779]
1779
(1779,)


In [67]:
# 사용자 아이디가 1인 사람의 데이터만 boolean 인덱싱
data_1 = data[data[:,0]==1]
data_2 = data[data[:,0]==2]
data_3 = data[data[:,0]==3]
data_4 = data[data[:,0]==4]
data_5 = data[data[:,0]==5]

In [68]:
print(data_1.shape) # 53행, 즉 아이디 1이 53개의 리뷰 남김

(53, 4)


In [69]:
data_1[:,2] # 1번 사람이 매긴 평점 슬라이싱

array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 4, 3, 3,
       5, 5, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       4, 5, 5, 4, 5, 4, 4, 4, 4], dtype=int64)

In [71]:
data_avg1 = data_1[:,2].mean() # 1번 사람이 남긴 평점의 평균
data_avg2 = data_2[:,2].mean()
data_avg3 = data_3[:,2].mean()
data_avg4 = data_4[:,2].mean()
data_avg5 = data_5[:,2].mean()

In [73]:
# 전체 데이터 아이디별 평균 평점 총 1779개

cnt = 0

for i in user_id:
    data_rating = data[data[:,0]==i]
    data_rating_mean = data_rating[:,2].mean()
    print(data_rating_mean)

4.188679245283019
3.7131782945736433
3.9019607843137254
4.190476190476191
3.1464646464646466
3.9014084507042255
4.32258064516129
3.884892086330935
3.7358490566037736
4.114713216957606
3.2773722627737225
3.8260869565217392
3.388888888888889
3.32
3.3233830845771144
3.0285714285714285
4.075829383886256
3.6491803278688524
3.5725490196078433
4.083333333333333
2.909090909090909
3.0673400673400675
3.3157894736842106
3.948529411764706
3.7411764705882353
2.96
4.171428571428572
3.7570093457943927
3.5833333333333335
3.488372093023256
3.73109243697479
3.625
3.498721227621483
3.8658536585365852
3.54040404040404
4.199430199430199
3.69811320754717
3.58
3.564516129032258
3.4479166666666665
3.48
3.74025974025974
4.125
3.6321243523316062
2.946127946127946
4.219512195121951
3.909090909090909
3.068561872909699
3.712962962962963
3.0697674418604652
3.825
3.5569620253164556
4.2368421052631575
4.025
4.12
3.970149253731343
2.90625
3.9725400457665905
3.4741784037558685
3.414285714285714
2.7777777777777777
3.566

4.0
4.13855421686747
3.231404958677686
4.391304347826087
3.641509433962264
4.29559748427673
3.95
2.9523809523809526
4.473684210526316
3.3157894736842106
3.8518518518518516
3.652173913043478
3.1501340482573728
3.396103896103896
3.5238095238095237
3.0940766550522647
4.049180327868853
4.03030303030303
4.16
3.1882352941176473
4.346153846153846
3.484126984126984
3.9393939393939394
3.5
3.5849056603773586
3.8333333333333335
4.127659574468085
3.9545454545454546
4.086956521739131
3.0
3.909090909090909
3.3240223463687153
3.0416666666666665
3.912280701754386
4.226744186046512
3.6801075268817205
4.0
4.055555555555555
3.5625
3.9038461538461537
3.371308016877637
4.254237288135593
3.7948717948717947
3.7941176470588234
3.5813953488372094
4.014925373134329
4.3107344632768365
4.058139534883721
3.7559681697612732
4.175438596491228
3.705
4.333333333333333
4.008264462809917
4.111111111111111
2.7142857142857144
3.1203703703703702
4.4772727272727275
3.8031496062992125
3.103896103896104
3.7231638418079096
3.6

3.3375850340136055
4.0
3.3698630136986303
2.696969696969697
4.0588235294117645
3.3857142857142857
3.6219512195121952
4.0
2.58955223880597
3.4702380952380953
4.1875
3.5106382978723403
2.1988188976377954
3.324324324324324
2.259259259259259
3.533333333333333
3.8333333333333335
3.9316770186335406
3.78125
3.7051282051282053
4.113636363636363
3.0878048780487806
4.326530612244898
4.03030303030303
3.4418262150220915
3.9749216300940438
3.462686567164179
3.1743119266055047
3.8661971830985915
3.777188328912467
3.6666666666666665
3.787341772151899
3.764625850340136
3.9550173010380623
3.2280701754385963
3.3666666666666667
3.7712082262210798
3.222413793103448
3.761904761904762
3.2213740458015265
3.216867469879518
4.145631067961165
3.849462365591398
4.796116504854369
4.343558282208589
3.386904761904762
4.42
3.813953488372093
3.267857142857143
3.74468085106383
3.662921348314607
3.9065934065934065
3.7566844919786098
3.3090128755364807
3.3726235741444865
4.30188679245283
3.772727272727273
3.368421052631

3.494565217391304
3.3018181818181818
3.431472081218274
3.9073170731707316
4.1
3.842857142857143
4.166666666666667
3.3122406639004147
3.79126213592233
3.1847826086956523
2.0833333333333335
3.4206128133704734
3.9642857142857144
3.573741007194245
3.652173913043478
3.4264150943396228
3.3934426229508197
3.0476190476190474
3.1338582677165356
3.0833333333333335
4.208791208791209
4.03030303030303
3.9444444444444446
3.1363636363636362
3.730769230769231
4.214285714285714
3.005714285714286
3.3555555555555556
3.4391143911439115
2.9791666666666665
3.745011086474501
3.4923076923076923
2.264957264957265
3.8423076923076924
2.7760416666666665
2.9705882352941178
3.5849056603773586
3.780580075662043
2.8
3.988235294117647
4.205128205128205
3.658802177858439
2.472049689440994
2.6810344827586206
3.5
4.28755364806867
3.0625
4.061302681992337
3.064516129032258
3.2301587301587302
3.442953020134228
3.8421052631578947
3.647887323943662
3.2
3.3703703703703702
3.92
4.446808510638298
3.8
3.48
3.888888888888889
3.41

In [74]:
# 각 유저가 매긴 평균평점ㄴ

data_usra = []

for i in user_id:
    data_rating = data[data[:,0]==i]
    data_rating_mean = data_rating[:,2].mean()
    data_usra.append([i,data_rating_mean])

print(data_usra)

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606], [11, 3.2773722627737225], [12, 3.8260869565217392], [13, 3.388888888888889], [14, 3.32], [15, 3.3233830845771144], [16, 3.0285714285714285], [17, 4.075829383886256], [18, 3.6491803278688524], [19, 3.5725490196078433], [20, 4.083333333333333], [21, 2.909090909090909], [22, 3.0673400673400675], [23, 3.3157894736842106], [24, 3.948529411764706], [25, 3.7411764705882353], [26, 2.96], [27, 4.171428571428572], [28, 3.7570093457943927], [29, 3.5833333333333335], [30, 3.488372093023256], [31, 3.73109243697479], [32, 3.625], [33, 3.498721227621483], [34, 3.8658536585365852], [35, 3.54040404040404], [36, 4.199430199430199], [37, 3.69811320754717], [38, 3.58], [39, 3.564516129032258], [40, 3.4479166666666665], [41, 3.48], [42, 3.74025974025974], [43, 4.12